/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "element-dark2nd-card": "var(--element-dark2nd-card)",
        "element-dark2nd-text": "var(--element-dark2nd-text)",
        "element-darkbackground": "var(--element-darkbackground)",
        "element-darkcard": "var(--element-darkcard)",
        "element-darkline": "var(--element-darkline)",
        "element-light2nd-text": "var(--element-light2nd-text)",
        "element-lightbackground": "var(--element-lightbackground)",
        "element-lightdefault-nav-icon": "var(--element-lightdefault-nav-icon)",
        "element-lightform-line": "var(--element-lightform-line)",
        "element-lightinactive-text": "var(--element-lightinactive-text)",
        "element-lightline": "var(--element-lightline)",
        "element-lightwhite": "var(--element-lightwhite)",
        "primarydark-blue": "var(--primarydark-blue)",
        "primarypin-ai-light-pink": "var(--primarypin-ai-light-pink)",
        "primarypin-ai-pink": "var(--primarypin-ai-pink)",
        "primaryreal-black": "var(--primaryreal-black)",
        secondarybeige: "var(--secondarybeige)",
        "secondarygrey-ash": "var(--secondarygrey-ash)",
        "secondaryink-blue": "var(--secondaryink-blue)",
        "secondarylight-beige": "var(--secondarylight-beige)",
        "secondarylight-grass-green": "var(--secondarylight-grass-green)",
        "secondarylight-grey-ash": "var(--secondarylight-grey-ash)",
        "secondarylight-ink-blue": "var(--secondarylight-ink-blue)",
        "secondarylight-lime": "var(--secondarylight-lime)",
        "secondarylight-linkedin": "var(--secondarylight-linkedin)",
        "secondarylight-lite-blue": "var(--secondarylight-lite-blue)",
        "secondarylight-mint": "var(--secondarylight-mint)",
        "secondarylight-orange": "var(--secondarylight-orange)",
        "secondarylight-pink": "var(--secondarylight-pink)",
        "secondarylight-purple": "var(--secondarylight-purple)",
        "secondarylight-raspberry-red": "var(--secondarylight-raspberry-red)",
        "secondarylight-red-alert": "var(--secondarylight-red-alert)",
        "secondarylight-violet": "var(--secondarylight-violet)",
        "secondarylight-yellow": "var(--secondarylight-yellow)",
        secondarylime: "var(--secondarylime)",
        secondarylinkedin: "var(--secondarylinkedin)",
        "secondarylite-blue": "var(--secondarylite-blue)",
        secondarymint: "var(--secondarymint)",
        secondaryorange: "var(--secondaryorange)",
        secondarypink: "var(--secondarypink)",
        secondarypurple: "var(--secondarypurple)",
        "secondaryraspberry-red": "var(--secondaryraspberry-red)",
        "secondaryred-alert": "var(--secondaryred-alert)",
        secondaryviolet: "var(--secondaryviolet)",
        secondaryyellow: "var(--secondaryyellow)",
        "variable-collection-color": "var(--variable-collection-color)",
        "variable-collection-glass": "var(--variable-collection-glass)",
        "variable-collection-glass-thick":
          "var(--variable-collection-glass-thick)",
        "variable-collection-light-bg": "var(--variable-collection-light-bg)",
        "variable-collection-stoke-modal-edge":
          "var(--variable-collection-stoke-modal-edge)",
      },
      fontFamily: {
        "extra-large-24px-bold": "var(--extra-large-24px-bold-font-family)",
        "extra-large-24px-medium": "var(--extra-large-24px-medium-font-family)",
        "extra-large-24px-regular":
          "var(--extra-large-24px-regular-font-family)",
        "extra-large-24px-semi-bold":
          "var(--extra-large-24px-semi-bold-font-family)",
        "extra-small-12px-bold": "var(--extra-small-12px-bold-font-family)",
        "extra-small-12px-medium": "var(--extra-small-12px-medium-font-family)",
        "extra-small-12px-regular":
          "var(--extra-small-12px-regular-font-family)",
        "extra-small-12px-semi-bold":
          "var(--extra-small-12px-semi-bold-font-family)",
        "large-20px-bold": "var(--large-20px-bold-font-family)",
        "large-20px-medium": "var(--large-20px-medium-font-family)",
        "large-20px-regular": "var(--large-20px-regular-font-family)",
        "large-20px-semi-bold": "var(--large-20px-semi-bold-font-family)",
        "medium-16px-bold": "var(--medium-16px-bold-font-family)",
        "medium-16px-medium": "var(--medium-16px-medium-font-family)",
        "medium-16px-regular": "var(--medium-16px-regular-font-family)",
        "medium-16px-semi-bold": "var(--medium-16px-semi-bold-font-family)",
        "side-bar-menu-item": "var(--side-bar-menu-item-font-family)",
        "small-14px-bold": "var(--small-14px-bold-font-family)",
        "small-14px-medium": "var(--small-14px-medium-font-family)",
        "small-14px-regular": "var(--small-14px-regular-font-family)",
        "small-14px-semi-bold": "var(--small-14px-semi-bold-font-family)",
      },
      boxShadow: {
        "dark-shadow": "var(--dark-shadow)",
        "dark-text-shadow": "var(--dark-text-shadow)",
        "drop-shadow-100": "var(--drop-shadow-100)",
        "drop-shadow-200": "var(--drop-shadow-200)",
        "pink-modal-shadow": "var(--pink-modal-shadow)",
        "pink-shadow-1": "var(--pink-shadow-1)",
        "pink-shadow-2": "var(--pink-shadow-2)",
        "pink-shadow3": "var(--pink-shadow3)",
        shadow: "var(--shadow)",
      },
    },
  },
  plugins: [],
};
